#ifndef __BD_COMM_M2M_H__
#define __BD_COMM_M2M_H__

#include "bd_common.h"
#include "bd_errno.h"

#ifdef __cplusplus
#if __cplusplus
extern "C"
{
#endif
#endif /* __cplusplus */

typedef enum bdEN_M2MU_ERR_CODE_E
{
    ERR_M2M_FAILED_NOTENABLE = 64,   /* device or channel not enable*/
    ERR_M2M_FAILED_NOTDISABLE,       /* device not disable*/
    ERR_M2M_FAILED_CHNOTDISABLE,     /* channel not disable*/
    ERR_M2M_NORM_UNMATCH,            /* video norm of ADC and M2MU is unmatch*/
    ERR_M2M_INVALID_WAYID,           /* invlalid way ID     */
    ERR_M2M_INVALID_PHYCHNID,        /* invalid phychn id*/
    ERR_M2M_FAILED_NOTBIND,          /* device or channel not bind */
    ERR_M2M_FAILED_BINDED,           /* device or channel not unbind */
	ERR_M2M_FAILED_TIMEOUT,			/* init or select fail */
	ERR_M2M_FAILED_INTERNAL,			/* msg error */
} EN_M2MU_ERR_CODE_E;


#define BD_ERR_M2M_INVALID_PARA          BD_DEF_ERR(BD_ID_M2MU, EN_ERR_LEVEL_ERROR, EN_ERR_ILLEGAL_PARAM)
#define BD_ERR_M2M_INVALID_DEM2MD         BD_DEF_ERR(BD_ID_M2MU, EN_ERR_LEVEL_ERROR, EN_ERR_INVALID_DEM2MD)
#define BD_ERR_M2M_INVALID_CHNID         BD_DEF_ERR(BD_ID_M2MU, EN_ERR_LEVEL_ERROR, EN_ERR_INVALID_CHNID)
#define BD_ERR_M2M_INVALID_NULL_PTR      BD_DEF_ERR(BD_ID_M2MU, EN_ERR_LEVEL_ERROR, EN_ERR_NULL_PTR)
#define BD_ERR_M2M_FAILED_NOTCONFIG      BD_DEF_ERR(BD_ID_M2MU, EN_ERR_LEVEL_ERROR, EN_ERR_NOT_CONFIG)
#define BD_ERR_M2M_SYS_NOTREADY          BD_DEF_ERR(BD_ID_M2MU, EN_ERR_LEVEL_ERROR, EN_ERR_SYS_NOTREADY)
#define BD_ERR_M2M_BUF_EMPTY             BD_DEF_ERR(BD_ID_M2MU, EN_ERR_LEVEL_ERROR, EN_ERR_BUF_EMPTY)
#define BD_ERR_M2M_BUF_FULL              BD_DEF_ERR(BD_ID_M2MU, EN_ERR_LEVEL_ERROR, EN_ERR_BUF_FULL)
#define BD_ERR_M2M_NOMEM                 BD_DEF_ERR(BD_ID_M2MU, EN_ERR_LEVEL_ERROR, EN_ERR_NOMEM)
#define BD_ERR_M2M_NOT_SUPPORT           BD_DEF_ERR(BD_ID_M2MU, EN_ERR_LEVEL_ERROR, EN_ERR_NOT_SUPPORT)
#define BD_ERR_M2M_BUSY                  BD_DEF_ERR(BD_ID_M2MU, EN_ERR_LEVEL_ERROR, EN_ERR_BUSY)
#define BD_ERR_M2M_NOT_PERM              BD_DEF_ERR(BD_ID_M2MU, EN_ERR_LEVEL_ERROR, EN_ERR_NOT_PERM)

#define BD_ERR_M2M_FAILED_NOTENABLE      BD_DEF_ERR(BD_ID_M2MU, EN_ERR_LEVEL_ERROR, ERR_M2M_FAILED_NOTENABLE)
#define BD_ERR_M2M_FAILED_NOTDISABLE     BD_DEF_ERR(BD_ID_M2MU, EN_ERR_LEVEL_ERROR, ERR_M2M_FAILED_NOTDISABLE)
#define BD_ERR_M2M_FAILED_CHNOTDISABLE   BD_DEF_ERR(BD_ID_M2MU, EN_ERR_LEVEL_ERROR, ERR_M2M_FAILED_CHNOTDISABLE)
#define BD_ERR_M2M_NORM_UNMATCH          BD_DEF_ERR(BD_ID_M2MU, EN_ERR_LEVEL_ERROR, ERR_M2M_NORM_UNMATCH)
#define BD_ERR_M2M_INVALID_WAYID         BD_DEF_ERR(BD_ID_M2MU, EN_ERR_LEVEL_ERROR, ERR_M2M_INVALID_WAYID)
#define BD_ERR_M2M_INVALID_PHYCHNID      BD_DEF_ERR(BD_ID_M2MU, EN_ERR_LEVEL_ERROR, ERR_M2M_INVALID_PHYCHNID)
#define BD_ERR_M2M_FAILED_NOTBIND        BD_DEF_ERR(BD_ID_M2MU, EN_ERR_LEVEL_ERROR, ERR_M2M_FAILED_NOTBIND)
#define BD_ERR_M2M_FAILED_BINDED         BD_DEF_ERR(BD_ID_M2MU, EN_ERR_LEVEL_ERROR, ERR_M2M_FAILED_BINDED)
#define BD_ERR_M2M_FAILED_TIMEOUT        BD_DEF_ERR(BD_ID_M2MU, EN_ERR_LEVEL_ERROR, ERR_M2M_FAILED_TIMEOUT)
#define BD_ERR_M2M_FAILED_INTERNAL       BD_DEF_ERR(BD_ID_M2MU, EN_ERR_LEVEL_ERROR, ERR_M2M_FAILED_INTERNAL)


#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif /* __cplusplus */

#endif 


