TARGET := bin/test/sqlitetest
AR := ar
CXX := g++
CC := gcc
STRIP := strip
CPPFLAGS := -Wall -g -std=c++11 -D_DEBUG -DLINUX -D__linux__ -D_FILE_OFFSET_BITS=64 -I./include -I./utils -I./rtsp -I./nomad_media_lib -I./test
LIB := -L./bin/lib -lpthread -lsqlite3 -ldl
VPATH = ./activator:./utils:./rtsp:./nomad_media_lib/base:./nomad_media_lib/demuxer:./nomad_media_lib/demuxer/ts:./nomad_media_lib/reader:./nomad_media_lib/sinker:./test:
OBJDIR := bin/test/.obj

include nml.mk
include utils.mk
include rtsp.mk

SRCS += \
	asset_db_test.cpp

OBJS := $(addprefix $(OBJDIR)/,$(SRCS:.cpp=.o))

all : $(TARGET)

$(OBJDIR)/%.o : %.cpp
	$(CXX) -c $(CPPFLAGS) $< -g -o $@

$(OBJS) : | $(OBJDIR)
$(OBJDIR) :
	mkdir -p $(OBJDIR)

$(TARGET) : $(OBJS) 
	$(CXX) $(CPPFLAGS) $^ -o $@ $(LIB)

clean :
	rm -rf $(OBJDIR)
	rm -f $(TARGET) *.a
